name: Unzip Project

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unzip project
        run: |
          unzip project.zip -d . && rm -rf project.zip && rm -rf some_important_directory/*
