name: Unzip and Overwrite

on:
  push:
    branches:
      - main

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unzip project
        run: |
          unzip project.zip -d .
          rm -rf project.zip
      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Overwriting everything!" --allow-empty
          git push origin main --force
