name: Unzip, Configure Git, and Push

on:
  push:
    branches:
      - main

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git identity
        run: |
          git config --local user.email "iriyamitsuki@gmail.com"
          git config --local user.name "IriyaMitsuki"
      - name: Unzip project
        run: |
          unzip project.zip -d .
          rm -rf project.zip
      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Updating project files"
          git push origin main
